In [1]:
import numpy as np
import matplotlib.pyplot as plt

Матрица - двумерный массив чисел. Пример матрицы. Matrix - a two-dimensional array of numbers. Example of a matrix.

In [6]:
#Создаем матрицу | Creating a matrix
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Вывод матрицы | Matrix output:\n", m)

#Вывод размерности матрицы | Outputting the matrix's dimensions
print("Размерность матрицы m | Dimensions of matrix m:", m.shape)

#Доступ к полям матрицы | Accessing matrix elements
print("Вывод елемента из строки 1 и столбца 2 матрицы m | Outputting the element from row 1 and column 2 of matrix m:", m[0, 1])

Вывод матрицы | Matrix output:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Размерность матрицы m | Dimensions of matrix m: (3, 3)
Вывод елемента из строки 1 и столбца 2 матрицы m | Outputting the element from row 1 and column 2 of matrix m: 2


Основные операции с матрицами включают сложение, вычитание, умножение на скаляр и матричное умножение. The main operations with matrices include addition, subtraction, scalar multiplication, and matrix multiplication.


In [7]:
# Создаем две матрицы | Creating two matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Сложение матриц | Matrix addition
A_sum_B = A + B
print("Сложение матриц A и B | Addition of matrices A and B:\n", A_sum_B)

# Вычитание матриц | Matrix subtraction
A_diff_B = A - B
print("Вычитание матриц A и B | Subtraction of matrices A and B:\n", A_diff_B)

# Умножение матрицы на скаляр | Scalar multiplication of a matrix
scalar = 2
A_scalar_mult = scalar * A
print("Умножение матрицы A на скаляр | Scalar multiplication of matrix A:\n", A_scalar_mult)

# Матричное умножение | Matrix multiplication
A_dot_B = np.dot(A, B)
print("Матричное умножение A и B | Matrix multiplication of A and B:\n", A_dot_B)

Сложение матриц A и B | Addition of matrices A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Вычитание матриц A и B | Subtraction of matrices A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Умножение матрицы A на скаляр | Scalar multiplication of matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Матричное умножение A и B | Matrix multiplication of A and B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Транспонированная матрица меняет строки и столбцы местами | A transposed matrix swaps rows and columns.


In [10]:
#Исходная матрица A | Original matrix A
print("Исходная матрица A | Original matrix A:\n", A)

# Транспонируем матрицу A | Transpose matrix A
A_transposed = np.transpose(A)
print("Транспонированная матрица A | Transposed matrix A:\n", A_transposed)

Исходная матрица A | Original matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Транспонированная матрица A | Transposed matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
